function generateHTML(url, vtt, title) {
    const html = `
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Player HLS com Legendas</title><link href="https://vjs.zencdn.net/8.10.0/video-js.css" rel="stylesheet"><style>*{box-sizing:border-box}body{background-color:#000;color:#fff;display:flex;justify-content:center;align-items:center;min-height:100vh;margin:0;font-family:Arial,sans-serif}.home-container{width:90%;max-width:1200px;margin:20px auto;padding:20px;display:flex;flex-direction:column;align-items:center}.container{width:100%;aspect-ratio:16/9;margin:20px 0}.video-js{width:100%;height:100%}.video-title{font-size:24px;margin-bottom:20px;text-align:center}.loading-screen{position:fixed;top:0;left:0;width:100%;height:100%;background-color:#fff;display:flex;justify-content:center;align-items:center;z-index:9999}.spinner{border:8px solid #f3f3f3;border-top:8px solid #3498db;border-radius:50%;width:60px;height:60px;animation:spin 1s linear infinite}@keyframes spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}.error-message{color:#ff0000;text-align:center;margin-top:10px;display:none}@media (max-width:768px){.home-container{width:95%;padding:10px}.video-title{font-size:20px}}@media (max-width:480px){.video-title{font-size:18px}}</style></head><body><div class="home-container"><h1 class="video-title">${title || 'Player de Vídeo'}</h1><div class="container"><video id="my-video" class="video-js vjs-default-skin" controls preload="auto" data-setup='{"fluid":true}'><source src="${url}" type="application/x-mpegURL">${vtt ? `<track kind="subtitles" src="${vtt}" srclang="pt" label="Português" default>` : ''}</video></div><div class="error-message">Ocorreu um erro ao carregar o vídeo.</div><div class="loading-screen"><div class="spinner"></div></div></div><script src="https://vjs.zencdn.net/8.10.0/video.min.js"></script><script>var player=videojs('my-video');player.ready(function(){document.querySelector('.loading-screen').style.display='none';let videoTitle="${title || ''}";if(videoTitle){document.querySelector('.video-title').textContent=videoTitle}});player.on('error',function(){document.querySelector('.error-message').style.display='block';document.querySelector('.loading-screen').style.display='none'});player.isFullscreen(false);</script></body></html>
    `;
    return html.replace(/\s+/g, ' ').replace(/> </g, '><').trim();
}

function createAndRedirectToPage(url, vtt, title) {
    const htmlContent = generateHTML(url, vtt, title);
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const urlObj = URL.createObjectURL(blob);
    window.location.href = urlObj;
}